#ifndef TVIL_GLOBALDATA_H
#define TVIL_GLOBALDATA_H

#define _a TVIL_a
#define _a2 TVIL_a2
#define _a3 TVIL_a3
#define _a4 TVIL_a4
#define _a5 TVIL_a5
#define _a6 TVIL_a6
#define _a7 TVIL_a7
#define _a8 TVIL_a8
#define _a9 TVIL_a9
#define _maxerr TVIL_maxerr
#define _err_H TVIL_err_H
#define _maxerr_noH TVIL_maxerr_noH
#define _Ug TVIL_Ug
#define _Vg TVIL_Vg
#define _Wg TVIL_Wg
#define _Xg TVIL_Xg
#define _Yg TVIL_Yg
#define _Zg TVIL_Zg
#define _lnbarUg TVIL_lnbarUg
#define _lnbarVg TVIL_lnbarVg
#define _lnbarWg TVIL_lnbarWg
#define _lnbarXg TVIL_lnbarXg
#define _lnbarYg TVIL_lnbarYg
#define _lnbarZg TVIL_lnbarZg
#define _isAligned TVIL_isAligned
#define _isInitialized TVIL_isInitialized
#define _evalMode TVIL_evalMode
#define _reAxisOK TVIL_reAxisOK
#define _poleAt1  TVIL_poleAt1 
#define _doAnalytic TVIL_doAnalytic
#define _forceContour TVIL_forceContour
#define _forceDefault TVIL_forceDefault
#define _status TVIL_status
#define _u TVIL_u
#define _v TVIL_v
#define _w TVIL_w
#define _x TVIL_x
#define _y TVIL_y
#define _z TVIL_z
#define _qq TVIL_qq
#define _II TVIL_II
#define _FBAR TVIL_FBAR
#define _E TVIL_E
#define _G TVIL_G
#define _H TVIL_H
#define _arglist TVIL_arglist
#define _integrateII TVIL_integrateII
#define _integrateFBAR TVIL_integrateFBAR
#define _integrateE TVIL_integrateE
#define _integrateG TVIL_integrateG
#define _integrateH TVIL_integrateH
#define _nIfuns TVIL_nIfuns
#define _nFBARfuns TVIL_nFBARfuns
#define _nEfuns TVIL_nEfuns
#define _nGfuns TVIL_nGfuns
#define _nHfuns TVIL_nHfuns
#define _ifun TVIL_ifun
#define _fbarfun TVIL_fbarfun
#define _efun TVIL_efun
#define _gfun TVIL_gfun
#define _hfun TVIL_hfun
#define _Iderivative TVIL_Iderivative
#define _FBARderivative TVIL_FBARderivative
#define _Gderivative TVIL_Gderivative
#define _Hderivative TVIL_Hderivative
#define _tPole TVIL_tPole
#define _nPoles TVIL_nPoles
#define _imDispl TVIL_imDispl
#define _tInit TVIL_tInit
#define _aParameter TVIL_aParameter
#define _precisionGoal TVIL_precisionGoal
#define _nStepsStart TVIL_nStepsStart
#define _nStepsMaxCon TVIL_nStepsMaxCon
#define _nStepsMaxVar TVIL_nStepsMaxVar
#define _nStepsMin TVIL_nStepsMin
#define _RKstepper6 TVIL_RKstepper6
#define _RKstepper5 TVIL_RKstepper5
#define _printStyle TVIL_printStyle
#define _print3VILWarns TVIL_print3VILWarns
#define _printBold TVIL_printBold

#endif
